// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Agent {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// Base64-encoded Ed25519 public key
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Hub address
    #[prost(string, tag = "4")]
    pub primary_hub: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub version: i32,
    /// Embedded trust relations
    #[prost(message, optional, tag = "6")]
    pub trust: ::core::option::Option<TrustStore>,
    #[prost(string, tag = "7")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustStore {
    #[prost(message, repeated, tag = "1")]
    pub trusts: ::prost::alloc::vec::Vec<Trust>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trust {
    /// Address of trusted agent
    #[prost(string, tag = "1")]
    pub agent_address: ::prost::alloc::string::String,
    /// -1.0 to 1.0
    #[prost(float, tag = "2")]
    pub trust_level: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fragment {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// Address strings
    #[prost(string, repeated, tag = "2")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional transform address
    #[prost(string, tag = "3")]
    pub transform_address: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    /// SHA-256 hash
    #[prost(string, tag = "5")]
    pub content_hash: ::prost::alloc::string::String,
    /// Agent address
    #[prost(string, tag = "6")]
    pub creator_address: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub version: i32,
    /// Content timestamp
    #[prost(message, optional, tag = "8")]
    pub when: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "9")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Relation {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// Source entity address
    #[prost(string, tag = "2")]
    pub from_address: ::prost::alloc::string::String,
    /// Target entity address
    #[prost(string, tag = "3")]
    pub to_address: ::prost::alloc::string::String,
    /// RelationType enum as string
    #[prost(string, tag = "4")]
    pub relation_type: ::prost::alloc::string::String,
    /// Agent address
    #[prost(string, tag = "5")]
    pub creator_address: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub version: i32,
    #[prost(string, tag = "7")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Was 'description'
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    /// TagCategory enum as string
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
    /// Agent address
    #[prost(string, tag = "5")]
    pub creator_address: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub version: i32,
    #[prost(string, tag = "7")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transform {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Target format
    #[prost(string, tag = "5")]
    pub transform_to: ::prost::alloc::string::String,
    /// Source format
    #[prost(string, tag = "6")]
    pub transform_from: ::prost::alloc::string::String,
    /// JSON config
    #[prost(string, tag = "7")]
    pub additional_data: ::prost::alloc::string::String,
    /// Creator agent address
    #[prost(string, tag = "8")]
    pub agent_address: ::prost::alloc::string::String,
    #[prost(int32, tag = "9")]
    pub version: i32,
    #[prost(string, tag = "10")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Agents
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateAgentRequest {
    /// Optional, will be generated if empty
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub primary_hub: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub signature: ::prost::alloc::string::String,
    /// For validation (not stored)
    #[prost(string, tag = "6")]
    pub created_by: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentsRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
    #[prost(string, tag = "2")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentsResponse {
    #[prost(message, repeated, tag = "1")]
    pub agents: ::prost::alloc::vec::Vec<Agent>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
}
/// Fragments
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFragmentRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub transform_address: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    /// Creator agent address
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub when: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "7")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFragmentRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchFragmentsRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    #[prost(string, tag = "4")]
    pub cursor: ::prost::alloc::string::String,
}
/// Relations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRelationRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub relation_type: ::prost::alloc::string::String,
    /// Creator agent address
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRelationRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
}
/// Tags
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTagRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    /// TagCategory enum as string
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
    /// Creator agent address
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTagRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTagsRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
    #[prost(string, tag = "2")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTagsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<Tag>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
}
/// Transforms
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTransformRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub transform_to: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub transform_from: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub additional_data: ::prost::alloc::string::String,
    /// Creator agent address
    #[prost(string, tag = "8")]
    pub agent_address: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTransformRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
}
/// Trust (embedded in Agent, path finding via service)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustPathRequest {
    /// Agent address
    #[prost(string, tag = "1")]
    pub from_address: ::prost::alloc::string::String,
    /// Entity address
    #[prost(string, tag = "2")]
    pub to_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustPath {
    #[prost(string, tag = "1")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub hops: ::prost::alloc::vec::Vec<TrustPathHop>,
    #[prost(float, tag = "4")]
    pub effective_trust: f32,
    #[prost(int32, tag = "5")]
    pub depth: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustPathHop {
    #[prost(string, tag = "1")]
    pub agent_address: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub trust_level: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustScoreRequest {
    /// Entity to score
    #[prost(string, tag = "1")]
    pub entity_address: ::prost::alloc::string::String,
    /// Viewer perspective (agent address)
    #[prost(string, tag = "2")]
    pub viewer_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustScore {
    #[prost(string, tag = "1")]
    pub entity_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub viewer_address: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub score: f32,
    #[prost(int32, tag = "4")]
    pub path_count: i32,
    #[prost(message, optional, tag = "5")]
    pub best_path: ::core::option::Option<TrustPath>,
}
/// Discovery
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HubRegistration {
    #[prost(string, tag = "1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistrationResponse {
    #[prost(bool, tag = "1")]
    pub registered: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub hub_list: ::core::option::Option<HubList>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(string, tag = "1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub stats: ::core::option::Option<HubStats>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatResponse {
    #[prost(bool, tag = "1")]
    pub acknowledged: bool,
    #[prost(message, optional, tag = "2")]
    pub server_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HubStats {
    #[prost(int64, tag = "1")]
    pub entities_count: i64,
    #[prost(int64, tag = "2")]
    pub agents_count: i64,
    #[prost(int64, tag = "3")]
    pub fragments_count: i64,
    #[prost(double, tag = "4")]
    pub uptime_seconds: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HubInfo {
    #[prost(string, tag = "1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, repeated, tag = "6")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub stats: ::core::option::Option<HubStats>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HubList {
    #[prost(message, repeated, tag = "1")]
    pub hubs: ::prost::alloc::vec::Vec<HubInfo>,
    #[prost(int64, tag = "2")]
    pub version: i64,
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Federated Search
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FederatedSearchRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub min_results: i32,
    #[prost(bool, tag = "3")]
    pub federate: bool,
    #[prost(string, repeated, tag = "4")]
    pub tag_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResult {
    #[prost(message, optional, tag = "1")]
    pub fragment: ::core::option::Option<Fragment>,
    #[prost(string, tag = "2")]
    pub source_hub_id: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub relevance_score: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FederatedSearchResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SearchResult>,
    #[prost(message, repeated, tag = "2")]
    pub sources: ::prost::alloc::vec::Vec<SearchSource>,
    #[prost(bool, tag = "3")]
    pub federated: bool,
    #[prost(int32, tag = "4")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchSource {
    #[prost(string, tag = "1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// Generated client implementations.
pub mod hub_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct HubServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl HubServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> HubServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> HubServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            HubServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Agents
        pub async fn create_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateAgentRequest>,
        ) -> std::result::Result<tonic::Response<super::Agent>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CreateAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "CreateAgent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAgentRequest>,
        ) -> std::result::Result<tonic::Response<super::Agent>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetAgent"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_agents(
            &mut self,
            request: impl tonic::IntoRequest<super::ListAgentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAgentsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/ListAgents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "ListAgents"));
            self.inner.unary(req, path, codec).await
        }
        /// Fragments
        pub async fn create_fragment(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateFragmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Fragment>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CreateFragment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "CreateFragment"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_fragment(
            &mut self,
            request: impl tonic::IntoRequest<super::GetFragmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Fragment>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetFragment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetFragment"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_fragments(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchFragmentsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Fragment>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/SearchFragments",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "SearchFragments"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Relations
        pub async fn create_relation(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRelationRequest>,
        ) -> std::result::Result<tonic::Response<super::Relation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CreateRelation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "CreateRelation"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_relation(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRelationRequest>,
        ) -> std::result::Result<tonic::Response<super::Relation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetRelation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetRelation"));
            self.inner.unary(req, path, codec).await
        }
        /// Tags
        pub async fn create_tag(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTagRequest>,
        ) -> std::result::Result<tonic::Response<super::Tag>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CreateTag",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "CreateTag"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_tag(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTagRequest>,
        ) -> std::result::Result<tonic::Response<super::Tag>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetTag",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetTag"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_tags(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTagsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTagsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/ListTags",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "ListTags"));
            self.inner.unary(req, path, codec).await
        }
        /// Transforms
        pub async fn create_transform(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTransformRequest>,
        ) -> std::result::Result<tonic::Response<super::Transform>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CreateTransform",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "CreateTransform"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_transform(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTransformRequest>,
        ) -> std::result::Result<tonic::Response<super::Transform>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetTransform",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetTransform"));
            self.inner.unary(req, path, codec).await
        }
        /// Trust (path finding, score calculation)
        pub async fn calculate_trust_path(
            &mut self,
            request: impl tonic::IntoRequest<super::TrustPathRequest>,
        ) -> std::result::Result<tonic::Response<super::TrustPath>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/CalculateTrustPath",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("wisdom.hub.v1.HubService", "CalculateTrustPath"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_trust_score(
            &mut self,
            request: impl tonic::IntoRequest<super::TrustScoreRequest>,
        ) -> std::result::Result<tonic::Response<super::TrustScore>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetTrustScore",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetTrustScore"));
            self.inner.unary(req, path, codec).await
        }
        /// Discovery
        pub async fn register_hub(
            &mut self,
            request: impl tonic::IntoRequest<super::HubRegistration>,
        ) -> std::result::Result<
            tonic::Response<super::RegistrationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/RegisterHub",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "RegisterHub"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/Heartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "Heartbeat"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_known_hubs(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::HubList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/GetKnownHubs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "GetKnownHubs"));
            self.inner.unary(req, path, codec).await
        }
        /// Federated Search
        pub async fn federated_search(
            &mut self,
            request: impl tonic::IntoRequest<super::FederatedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FederatedSearchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wisdom.hub.v1.HubService/FederatedSearch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wisdom.hub.v1.HubService", "FederatedSearch"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod hub_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with HubServiceServer.
    #[async_trait]
    pub trait HubService: std::marker::Send + std::marker::Sync + 'static {
        /// Agents
        async fn create_agent(
            &self,
            request: tonic::Request<super::CreateAgentRequest>,
        ) -> std::result::Result<tonic::Response<super::Agent>, tonic::Status>;
        async fn get_agent(
            &self,
            request: tonic::Request<super::GetAgentRequest>,
        ) -> std::result::Result<tonic::Response<super::Agent>, tonic::Status>;
        async fn list_agents(
            &self,
            request: tonic::Request<super::ListAgentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAgentsResponse>,
            tonic::Status,
        >;
        /// Fragments
        async fn create_fragment(
            &self,
            request: tonic::Request<super::CreateFragmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Fragment>, tonic::Status>;
        async fn get_fragment(
            &self,
            request: tonic::Request<super::GetFragmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Fragment>, tonic::Status>;
        /// Server streaming response type for the SearchFragments method.
        type SearchFragmentsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Fragment, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn search_fragments(
            &self,
            request: tonic::Request<super::SearchFragmentsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SearchFragmentsStream>,
            tonic::Status,
        >;
        /// Relations
        async fn create_relation(
            &self,
            request: tonic::Request<super::CreateRelationRequest>,
        ) -> std::result::Result<tonic::Response<super::Relation>, tonic::Status>;
        async fn get_relation(
            &self,
            request: tonic::Request<super::GetRelationRequest>,
        ) -> std::result::Result<tonic::Response<super::Relation>, tonic::Status>;
        /// Tags
        async fn create_tag(
            &self,
            request: tonic::Request<super::CreateTagRequest>,
        ) -> std::result::Result<tonic::Response<super::Tag>, tonic::Status>;
        async fn get_tag(
            &self,
            request: tonic::Request<super::GetTagRequest>,
        ) -> std::result::Result<tonic::Response<super::Tag>, tonic::Status>;
        async fn list_tags(
            &self,
            request: tonic::Request<super::ListTagsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTagsResponse>,
            tonic::Status,
        >;
        /// Transforms
        async fn create_transform(
            &self,
            request: tonic::Request<super::CreateTransformRequest>,
        ) -> std::result::Result<tonic::Response<super::Transform>, tonic::Status>;
        async fn get_transform(
            &self,
            request: tonic::Request<super::GetTransformRequest>,
        ) -> std::result::Result<tonic::Response<super::Transform>, tonic::Status>;
        /// Trust (path finding, score calculation)
        async fn calculate_trust_path(
            &self,
            request: tonic::Request<super::TrustPathRequest>,
        ) -> std::result::Result<tonic::Response<super::TrustPath>, tonic::Status>;
        async fn get_trust_score(
            &self,
            request: tonic::Request<super::TrustScoreRequest>,
        ) -> std::result::Result<tonic::Response<super::TrustScore>, tonic::Status>;
        /// Discovery
        async fn register_hub(
            &self,
            request: tonic::Request<super::HubRegistration>,
        ) -> std::result::Result<
            tonic::Response<super::RegistrationResponse>,
            tonic::Status,
        >;
        async fn heartbeat(
            &self,
            request: tonic::Request<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        >;
        async fn get_known_hubs(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<super::HubList>, tonic::Status>;
        /// Federated Search
        async fn federated_search(
            &self,
            request: tonic::Request<super::FederatedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FederatedSearchResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct HubServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> HubServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for HubServiceServer<T>
    where
        T: HubService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/wisdom.hub.v1.HubService/CreateAgent" => {
                    #[allow(non_camel_case_types)]
                    struct CreateAgentSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::CreateAgentRequest>
                    for CreateAgentSvc<T> {
                        type Response = super::Agent;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::create_agent(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateAgentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetAgent" => {
                    #[allow(non_camel_case_types)]
                    struct GetAgentSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::GetAgentRequest>
                    for GetAgentSvc<T> {
                        type Response = super::Agent;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_agent(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAgentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/ListAgents" => {
                    #[allow(non_camel_case_types)]
                    struct ListAgentsSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::ListAgentsRequest>
                    for ListAgentsSvc<T> {
                        type Response = super::ListAgentsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListAgentsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::list_agents(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListAgentsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/CreateFragment" => {
                    #[allow(non_camel_case_types)]
                    struct CreateFragmentSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::CreateFragmentRequest>
                    for CreateFragmentSvc<T> {
                        type Response = super::Fragment;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateFragmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::create_fragment(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateFragmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetFragment" => {
                    #[allow(non_camel_case_types)]
                    struct GetFragmentSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::GetFragmentRequest>
                    for GetFragmentSvc<T> {
                        type Response = super::Fragment;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetFragmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_fragment(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetFragmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/SearchFragments" => {
                    #[allow(non_camel_case_types)]
                    struct SearchFragmentsSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::ServerStreamingService<
                        super::SearchFragmentsRequest,
                    > for SearchFragmentsSvc<T> {
                        type Response = super::Fragment;
                        type ResponseStream = T::SearchFragmentsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SearchFragmentsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::search_fragments(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchFragmentsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/CreateRelation" => {
                    #[allow(non_camel_case_types)]
                    struct CreateRelationSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::CreateRelationRequest>
                    for CreateRelationSvc<T> {
                        type Response = super::Relation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRelationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::create_relation(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateRelationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetRelation" => {
                    #[allow(non_camel_case_types)]
                    struct GetRelationSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::GetRelationRequest>
                    for GetRelationSvc<T> {
                        type Response = super::Relation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRelationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_relation(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRelationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/CreateTag" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTagSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::CreateTagRequest>
                    for CreateTagSvc<T> {
                        type Response = super::Tag;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::create_tag(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetTag" => {
                    #[allow(non_camel_case_types)]
                    struct GetTagSvc<T: HubService>(pub Arc<T>);
                    impl<T: HubService> tonic::server::UnaryService<super::GetTagRequest>
                    for GetTagSvc<T> {
                        type Response = super::Tag;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_tag(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/ListTags" => {
                    #[allow(non_camel_case_types)]
                    struct ListTagsSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::ListTagsRequest>
                    for ListTagsSvc<T> {
                        type Response = super::ListTagsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListTagsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::list_tags(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListTagsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/CreateTransform" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTransformSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::CreateTransformRequest>
                    for CreateTransformSvc<T> {
                        type Response = super::Transform;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTransformRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::create_transform(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTransformSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetTransform" => {
                    #[allow(non_camel_case_types)]
                    struct GetTransformSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::GetTransformRequest>
                    for GetTransformSvc<T> {
                        type Response = super::Transform;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTransformRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_transform(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTransformSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/CalculateTrustPath" => {
                    #[allow(non_camel_case_types)]
                    struct CalculateTrustPathSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::TrustPathRequest>
                    for CalculateTrustPathSvc<T> {
                        type Response = super::TrustPath;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrustPathRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::calculate_trust_path(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CalculateTrustPathSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetTrustScore" => {
                    #[allow(non_camel_case_types)]
                    struct GetTrustScoreSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::TrustScoreRequest>
                    for GetTrustScoreSvc<T> {
                        type Response = super::TrustScore;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrustScoreRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_trust_score(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTrustScoreSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/RegisterHub" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterHubSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::HubRegistration>
                    for RegisterHubSvc<T> {
                        type Response = super::RegistrationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HubRegistration>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::register_hub(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterHubSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/Heartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct HeartbeatSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::HeartbeatRequest>
                    for HeartbeatSvc<T> {
                        type Response = super::HeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::heartbeat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HeartbeatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/GetKnownHubs" => {
                    #[allow(non_camel_case_types)]
                    struct GetKnownHubsSvc<T: HubService>(pub Arc<T>);
                    impl<T: HubService> tonic::server::UnaryService<()>
                    for GetKnownHubsSvc<T> {
                        type Response = super::HubList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::get_known_hubs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetKnownHubsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wisdom.hub.v1.HubService/FederatedSearch" => {
                    #[allow(non_camel_case_types)]
                    struct FederatedSearchSvc<T: HubService>(pub Arc<T>);
                    impl<
                        T: HubService,
                    > tonic::server::UnaryService<super::FederatedSearchRequest>
                    for FederatedSearchSvc<T> {
                        type Response = super::FederatedSearchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FederatedSearchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as HubService>::federated_search(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FederatedSearchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for HubServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "wisdom.hub.v1.HubService";
    impl<T> tonic::server::NamedService for HubServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
